### ISSUE TITLE
Architecture "riscv64" is not supported

### ISSUE THREAD

**Issue by futurejones** [swift-riscv/swift-riscv64#1]
### Build Failure:- https://ci.swiftlang.xyz/job/swift-5.8-ubuntu-jammy-riscv64/1/console
**OS = Ubuntu**
**Release = 22.04 / Jammy**
**Swift Branch = release/5.8**

```bash
--- Build Script Analyzer ---
Skip build script analyzer
.build_script_log file not found at /home/build-user/build/.build_script_log
Traceback (most recent call last):
  File "/home/build-user/./swift/utils/build-script", line 800, in <module>
    exit_code = main()
                ^^^^^^
  File "/home/build-user/./swift/utils/build-script", line 795, in main
    return main_normal()
           ^^^^^^^^^^^^^
  File "/home/build-user/./swift/utils/build-script", line 642, in main_normal
    parser = driver_arguments.create_argument_parser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build-user/swift/utils/build_swift/build_swift/driver_arguments.py", line 585, in create_argument_parser
    default=StdlibDeploymentTarget.host_target().name,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build-user/swift/utils/swift_build_support/swift_build_support/targets.py", line 398, in host_target
    raise NotImplementedError('System "%s" with architecture "%s" is not '
NotImplementedError: System "Linux" with architecture "riscv64" is not supported
```

**Comment by futurejones** [comment]
Fixed by adding `riscv64` as a supported `Linux` architecture.
**Patch File** = [add-riscv64-to-targets.patch](https://github.com/swift-riscv/swift-riscv64/blob/main/patches/release-5.8-branch/add-riscv64-to-targets.patch)

**Comment by futurejones** [comment]
Fixed with https://github.com/apple/swift/pull/66530
